[package]
name = "polkadot-node-core-proposer"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
futures = "0.3.12"
futures-timer = "3.0.2"
tracing = "0.1.25"
polkadot-node-subsystem = { path = "../../subsystem" }
polkadot-overseer = { path = "../../overseer" }
polkadot-primitives = { path = "../../../primitives" }
sc-basic-authorship = { git = "https://github.com/paritytech/substrate", branch = "ao-update-wasmtime" }
sc-block-builder = { git = "https://github.com/paritytech/substrate", branch = "ao-update-wasmtime" }
sc-client-api = { git = "https://github.com/paritytech/substrate", branch = "ao-update-wasmtime" }
sc-telemetry = { git = "https://github.com/paritytech/substrate", branch = "ao-update-wasmtime" }
sp-api = { git = "https://github.com/paritytech/substrate", branch = "ao-update-wasmtime" }
sp-blockchain = { git = "https://github.com/paritytech/substrate", branch = "ao-update-wasmtime" }
sp-consensus = { git = "https://github.com/paritytech/substrate", branch = "ao-update-wasmtime" }
sp-core = { git = "https://github.com/paritytech/substrate", branch = "ao-update-wasmtime" }
sp-inherents = { git = "https://github.com/paritytech/substrate", branch = "ao-update-wasmtime" }
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "ao-update-wasmtime" }
sp-transaction-pool = { git = "https://github.com/paritytech/substrate", branch = "ao-update-wasmtime" }
prometheus-endpoint = { package = "substrate-prometheus-endpoint", git = "https://github.com/paritytech/substrate", branch = "ao-update-wasmtime" }
