[package]
name = "polkadot_common_slot_range"
version = "0.8.30"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
paste = "1.0"
parity-scale-codec = { version = "2.0.0", default-features = false, features = ["derive"] }
sp-std = { package = "sp-std", git = "https://github.com/paritytech/substrate", branch = "master", default-features = false }
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "master", default-features = false }

[features]
default = ["std"]
no_std = []
std = [
	"sp-std/std",
	"parity-scale-codec/std",
	"sp-runtime/std",
]
