[package]
name = "millau-bridge-node"
description = "Substrate node compatible with Millau runtime"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
build = "build.rs"
homepage = "https://substrate.dev"
repository = "https://github.com/paritytech/parity-bridges-common/"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"

[dependencies]
jsonrpc-core = "15.1.0"
structopt = "0.3.21"

# Bridge dependencies

bp-message-lane = { path = "../../../primitives/message-lane" }
bp-millau= { path = "../../../primitives/millau" }
bp-runtime = { path = "../../../primitives/runtime" }
millau-runtime = { path = "../runtime" }
pallet-message-lane = { path = "../../../modules/message-lane" }
pallet-message-lane-rpc = { path = "../../../modules/message-lane/rpc" }

# Substrate Dependencies

frame-benchmarking = { git = "https://github.com/paritytech/substrate", branch = "ao-update-wasmtime" }
frame-benchmarking-cli = { git = "https://github.com/paritytech/substrate", branch = "ao-update-wasmtime" }
sc-basic-authorship = { git = "https://github.com/paritytech/substrate", branch = "ao-update-wasmtime" }
sc-cli = { git = "https://github.com/paritytech/substrate", features = ["wasmtime"] , branch = "ao-update-wasmtime" }
sc-client-api = { git = "https://github.com/paritytech/substrate", branch = "ao-update-wasmtime" }
sc-consensus = { git = "https://github.com/paritytech/substrate", branch = "ao-update-wasmtime" }
sc-consensus-aura = { git = "https://github.com/paritytech/substrate", branch = "ao-update-wasmtime" }
sc-executor = { git = "https://github.com/paritytech/substrate", branch = "ao-update-wasmtime" }
sc-finality-grandpa = { git = "https://github.com/paritytech/substrate", branch = "ao-update-wasmtime" }
sc-finality-grandpa-rpc = { git = "https://github.com/paritytech/substrate", branch = "ao-update-wasmtime" }
sc-keystore = { git = "https://github.com/paritytech/substrate", branch = "ao-update-wasmtime" }
sc-service = { git = "https://github.com/paritytech/substrate", branch = "ao-update-wasmtime" }
sc-rpc = { git = "https://github.com/paritytech/substrate", branch = "ao-update-wasmtime" }
sc-transaction-pool = { git = "https://github.com/paritytech/substrate", branch = "ao-update-wasmtime" }
sp-consensus = { git = "https://github.com/paritytech/substrate", branch = "ao-update-wasmtime" }
sp-consensus-aura = { git = "https://github.com/paritytech/substrate", branch = "ao-update-wasmtime" }
sp-core = { git = "https://github.com/paritytech/substrate", branch = "ao-update-wasmtime" }
sp-inherents = { git = "https://github.com/paritytech/substrate", branch = "ao-update-wasmtime" }
sp-finality-grandpa = { git = "https://github.com/paritytech/substrate", branch = "ao-update-wasmtime" }
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "ao-update-wasmtime" }
substrate-frame-rpc-system = { git = "https://github.com/paritytech/substrate", branch = "ao-update-wasmtime" }

[build-dependencies]
build-script-utils = { package = "substrate-build-script-utils", version = "2.0" }
frame-benchmarking-cli = { git = "https://github.com/paritytech/substrate", branch = "ao-update-wasmtime" }
vergen = "3.1.0"

[features]
default = []

# TODO: https://github.com/paritytech/parity-bridges-common/issues/390
# I've left the feature flag here to test our CI configuration
runtime-benchmarks = [
	# "millau-runtime/runtime-benchmarks",
]
