[package]
name = "rococo-runtime"
version = "0.8.30"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
build = "build.rs"

[dependencies]
parity-scale-codec = { version = "2.0.0", default-features = false, features = ["derive"] }
serde = { version = "1.0.123", default-features = false }
serde_derive = { version = "1.0.117", optional = true }
smallvec = "1.6.1"
hex-literal = "0.3.1"
log = { version = "0.4.14", default-features = false }

frame-support = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "ser-instrument" }
sp-api = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "ser-instrument" }
sp-io = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "ser-instrument" }
sp-std = { package = "sp-std", git = "https://github.com/paritytech/substrate", default-features = false , branch = "ser-instrument" }
sp-runtime = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "ser-instrument" }
sp-session = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "ser-instrument" }
sp-staking = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "ser-instrument" }
sp-core = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "ser-instrument" }
sp-version = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "ser-instrument" }

tx-pool-api = { package = "sp-transaction-pool", git = "https://github.com/paritytech/substrate", default-features = false , branch = "ser-instrument" }
block-builder-api = { package = "sp-block-builder", git = "https://github.com/paritytech/substrate", default-features = false , branch = "ser-instrument" }
inherents = { package = "sp-inherents", git = "https://github.com/paritytech/substrate", default-features = false , branch = "ser-instrument" }
offchain-primitives = { package = "sp-offchain", git = "https://github.com/paritytech/substrate", default-features = false , branch = "ser-instrument" }

babe-primitives = { package = "sp-consensus-babe", git = "https://github.com/paritytech/substrate", default-features = false , branch = "ser-instrument" }
beefy-primitives = { git = "https://github.com/paritytech/grandpa-bridge-gadget", branch = "master", default-features = false }
frame-executive = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "ser-instrument" }
pallet-authority-discovery = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "ser-instrument" }
pallet-authorship = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "ser-instrument" }
pallet-babe = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "ser-instrument" }
pallet-beefy = { git = "https://github.com/paritytech/grandpa-bridge-gadget", branch = "master", default-features = false }
pallet-balances = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "ser-instrument" }
pallet-grandpa = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "ser-instrument" }
pallet-im-online = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "ser-instrument" }
pallet-indices = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "ser-instrument" }
pallet-mmr = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "ser-instrument" }
pallet-mmr-primitives = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "ser-instrument" }
pallet-transaction-payment = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "ser-instrument" }
pallet-transaction-payment-rpc-runtime-api = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "ser-instrument" }
pallet-session = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "ser-instrument" }
pallet-staking = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "ser-instrument" }
pallet-staking-reward-curve = { package = "pallet-staking-reward-curve", git = "https://github.com/paritytech/substrate", branch = "ser-instrument" }
pallet-sudo = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "ser-instrument" }
pallet-timestamp = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "ser-instrument" }
pallet-offences = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "ser-instrument" }
pallet-proxy = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "ser-instrument" }
pallet-utility = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "ser-instrument" }
authority-discovery-primitives = { package = "sp-authority-discovery", git = "https://github.com/paritytech/substrate", default-features = false , branch = "ser-instrument" }

frame-system = {git = "https://github.com/paritytech/substrate", default-features = false , branch = "ser-instrument" }
frame-system-rpc-runtime-api = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "ser-instrument" }

runtime-common = { package = "polkadot-runtime-common", path = "../common", default-features = false }
primitives = { package = "polkadot-primitives", path = "../../primitives", default-features = false }
polkadot-parachain = { path = "../../parachain", default-features = false }
runtime-parachains = { package = "polkadot-runtime-parachains", path = "../parachains", default-features = false }

xcm = { package = "xcm", path = "../../xcm", default-features = false }
xcm-executor = { package = "xcm-executor", path = "../../xcm/xcm-executor", default-features = false }
xcm-builder = { package = "xcm-builder", path = "../../xcm/xcm-builder", default-features = false }

[build-dependencies]
substrate-wasm-builder = "3.0.0"

[features]
default = ["std"]
no_std = []
std = [
	"authority-discovery-primitives/std",
	"babe-primitives/std",
	"parity-scale-codec/std",
	"frame-executive/std",
	"pallet-authority-discovery/std",
	"pallet-authorship/std",
	"pallet-babe/std",
	"beefy-primitives/std",
	"pallet-balances/std",
	"pallet-beefy/std",
	"pallet-grandpa/std",
	"pallet-sudo/std",
	"pallet-mmr/std",
	"pallet-mmr-primitives/std",
	"pallet-indices/std",
	"pallet-im-online/std",
	"pallet-session/std",
	"pallet-staking/std",
	"pallet-offences/std",
	"pallet-timestamp/std",
	"pallet-transaction-payment/std",
	"pallet-transaction-payment-rpc-runtime-api/std",
	"inherents/std",
	"frame-support/std",
	"polkadot-parachain/std",
	"primitives/std",
	"runtime-common/std",
	"runtime-parachains/std",
	"sp-api/std",
	"sp-core/std",
	"sp-io/std",
	"sp-runtime/std",
	"sp-session/std",
	"sp-staking/std",
	"sp-std/std",
	"frame-system/std",
	"frame-system-rpc-runtime-api/std",
	"offchain-primitives/std",
	"block-builder-api/std",
	"tx-pool-api/std",
	"sp-version/std",
	"serde_derive",
	"serde/std",
	"xcm/std",
	"xcm-executor/std",
	"xcm-builder/std",
	"log/std",
]
# When enabled, the runtime api will not be build.
#
# This is required by Cumulus to access certain types of the
# runtime without clashing with the runtime api exported functions
# in WASM.
disable-runtime-api = []
runtime-benchmarks = [
	"runtime-common/runtime-benchmarks",
	"frame-support/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
	"pallet-babe/runtime-benchmarks",
	"pallet-balances/runtime-benchmarks",
	"pallet-grandpa/runtime-benchmarks",
	"pallet-im-online/runtime-benchmarks",
	"pallet-indices/runtime-benchmarks",
	"pallet-staking/runtime-benchmarks",
	"pallet-timestamp/runtime-benchmarks",
]
try-runtime = [
	"frame-executive/try-runtime",
	"frame-support/try-runtime",
	"frame-system/try-runtime",
	"pallet-authority-discovery/try-runtime",
	"pallet-authorship/try-runtime",
	"pallet-babe/try-runtime",
	"pallet-balances/try-runtime",
	"pallet-grandpa/try-runtime",
	"pallet-sudo/try-runtime",
	"pallet-indices/try-runtime",
	"pallet-im-online/try-runtime",
	"pallet-session/try-runtime",
	"pallet-staking/try-runtime",
	"pallet-offences/try-runtime",
	"pallet-timestamp/try-runtime",
	"pallet-transaction-payment/try-runtime",
	"runtime-common/try-runtime",
]
